name: ODC Daily JIRA Status

on:
  # Trigger on a cron schedule (every weekday at 10:00 AM IST)
  schedule:
    - cron: '30 4 * * 1-5'   # Adjusted for 10:00 AM IST in UTC
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run Bash Script
      run: bash devconsole/forum-devconsole.sh ${{ secrets.JIRA_PAT }} ${{ secrets.PERSONAL_SLACK_HOOK }}